### ISSUE TITLE
Create admin interface with evaluation of the answers

### ISSUE THREAD

**Issue by lewisdylan** [bumi/mshauri#43]
Admin should get an evaluation report of the answers and the users.

Technical implementation:
- [x] Users can have an optional boolean admin flag
- [x] Add [pundit](https://github.com/varvet/pundit) policies to allow CRUD operations and limit the scope depending on the user (`admin?`)
- [x] Use the same controllers for admins and normal users

**Comment by fsmanuel** [comment]
If you need help with pundit let me know and I can point you in the right direction.

**Comment by bumi** [comment]
worked in #48
