### ISSUE TITLE
Use IDs in recommendation URLs

### ISSUE THREAD

**Issue by bumi** [bumi/mshauri#65]
currently it seems we use the title in the recommendation URL. As those can contain special characters and whitespace we should use the ID instead.

**Comment by musayann** [comment]
@bumi the id is also in the link, we added the title just to beautify the link to make it easily understandable by users, but we retrieve the recommendation based on the id.

**Comment by bumi** [comment]
ok, but I'd still remove the title or somehow make it URL-safe whitespace and special characters can cause unexpected issues, no?
